<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>pahiv</string>
   </array>
  <key>name</key>
  <string>pahiv</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.pahiv</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#packet_meta</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#packet_definition</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(packet|both|in|out)</string>
          <key>name</key>
          <string>keyword.pahiv</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.block.pahiv</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.block.pahiv</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>meta.block.pahiv</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.block.pahiv</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.block.pahiv</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.line.pahiv</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>text.pahiv</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>meta.block.pahiv</string>
        </dict>
       </array>
    </dict>
    <key>packet_definition</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>([A-Za-z][A-Za-z0-9]*)([\x{0020}\t]+)(in|out|both)([\x{0020}\t]+)({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.pahiv</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pahiv</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.pahiv</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pahiv</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>meta.block.pahiv</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#packet_definition__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.block.pahiv</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>packet_definition__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>([A-Za-z][A-Za-z0-9]*)([\x{0020}\t]+)([A-Za-z][A-Za-z0-9]*)([\x{0020}\t]+)(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.pahiv</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pahiv</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.member.pahiv</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pahiv</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.annotation.pahiv</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#packet_definition__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.annotation.pahiv</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z][A-Za-z0-9]*)([\x{0020}\t]+)([A-Za-z][A-Za-z0-9]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.pahiv</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pahiv</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>variable.other.member.pahiv</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>packet_definition__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.definition.annotation.pahiv</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z][A-Za-z0-9]*)(:)([\x{0020}\t]+)([A-Za-z][A-Za-z0-9]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.annotation.identifier.pahiv</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>meta.annotation.identifier.pahiv</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pahiv</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>meta.annotation.parameters.pahiv</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z][A-Za-z0-9]*)</string>
          <key>name</key>
          <string>meta.annotation.identifier.pahiv</string>
        </dict>
       </array>
    </dict>
    <key>packet_meta</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(packet)([\x{0020}\t]*)(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.pahiv</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pahiv</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>meta.group.pahiv</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#packet_meta__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>meta.group.pahiv</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>packet_meta__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([A-Za-z][A-Za-z0-9]*)(\:)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.pahiv</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.pahiv</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>meta.group.pahiv</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z][A-Za-z0-9]*)</string>
          <key>name</key>
          <string>constant.language.pahiv</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(0[xX][0-9a-fA-F]+)</string>
          <key>name</key>
          <string>constant.language.pahiv</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>